# Uncomment the next line to define a global platform for your project
 platform :ios, '16.0'

target 'DSKit-Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DSKit-Example
  pod 'DSKit', :path => '../'

end
